#!/bin/bash
echo "Starting MirrorShuttle (Move Mode)..." | logger -t "mirrorshuttle-plugin"
nohup /usr/bin/mirrorshuttle --mode=move --config=/boot/config/plugins/mirsht/config.yaml --json 1>/dev/null 2>/tmp/mirrorshuttle.json &
sleep 1
