#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
BOOT="/boot/config/plugins/mirsht"
DOCROOT="/usr/local/emhttp/plugins/mirsht"

echo "Resetting MirrorShuttle configuration..."
echo "Resetting MirrorShuttle configuration..." | logger -t "mirrorshuttle-plugin"

cp -f $DOCROOT/defaults/default.cfg $BOOT/mirsht.cfg
cp -f $DOCROOT/defaults/default.yaml $BOOT/config.yaml

if [ -x /usr/local/emhttp/plugins/mirsht/scripts/write_config ]; then
    /usr/local/emhttp/plugins/mirsht/scripts/write_config
fi

echo "MirrorShuttle is now reset to defaults, reboot or reinstall plugin in case of any problems."
