#!/bin/bash

DOCROOT="/usr/local/emhttp/plugins/mirsht"

source "/boot/config/plugins/mirsht/mirsht.cfg"

echo "Writing MirrorShuttle configuration..."
echo "Writing MirrorShuttle configuration..." | logger -t "mirrorshuttle-plugin"

rm -f "/boot/config/plugins/dynamix/mirrorshuttle.cron"

if [ "$CRON" == "hourly" ]; then
    cp -f $DOCROOT/defaults/default.cron "/boot/config/plugins/dynamix/mirrorshuttle.cron"
    sed -i '/mirrorshuttle-cron/s,^\*,0,' "/boot/config/plugins/dynamix/mirrorshuttle.cron"
elif [ "$CRON" == "daily" ]; then
    cp -f $DOCROOT/defaults/default.cron "/boot/config/plugins/dynamix/mirrorshuttle.cron"
    sed -i "/mirrorshuttle-cron/s,^\* \*,0 ${CRONHOUR}," "/boot/config/plugins/dynamix/mirrorshuttle.cron"
elif [ "$CRON" == "weekly" ]; then
    cp -f $DOCROOT/defaults/default.cron "/boot/config/plugins/dynamix/mirrorshuttle.cron"
    sed -i "/mirrorshuttle-cron/s,^\* \* \* \* \*,0 ${CRONHOUR} \* \* ${CRONDOW}," "/boot/config/plugins/dynamix/mirrorshuttle.cron"
elif [ "$CRON" == "monthly" ]; then
    cp -f $DOCROOT/defaults/default.cron "/boot/config/plugins/dynamix/mirrorshuttle.cron"
    sed -i "/mirrorshuttle-cron/s,^\* \* \*,0 ${CRONHOUR} ${CRONDOM}," "/boot/config/plugins/dynamix/mirrorshuttle.cron"
else
    rm -f "/boot/config/plugins/dynamix/mirrorshuttle.cron"
fi

sleep 1
update_cron
sleep 1
